### ISSUE TITLE
Logo erstellen

### ISSUE THREAD

**Issue by singhnamandeep** [lukashecke/portfolio-management-software#25]

**Comment by singhnamandeep** [comment]
1. Idee
![image](https://user-images.githubusercontent.com/43607156/154569979-d23bedd1-dc07-43a8-b26c-0abcdfebec3e.png)

**Comment by lukashecke** [comment]
![grafik](https://user-images.githubusercontent.com/57808594/154570218-46f2d5c5-b55c-4d09-93f7-a570c463d1fc.png)

**Comment by lukashecke** [comment]
https://duckduckgo.com/?q=trading+logo&t=ffab&atb=v211-1&iar=images&iax=images&ia=images

**Comment by singhnamandeep** [comment]
https://99designs.de/profiles/aissama/designs/1720674

**Comment by lukashecke** [comment]
![firestocks_logo](https://user-images.githubusercontent.com/57808594/154583735-60af16e7-b97e-409b-a130-53c719f7f2e8.svg)

Ich habe echt lange daran gesessen, aber hier hast du das jetzt als svg

**Comment by lukashecke** [comment]
Mir ist gerade noch eine Idee gekommen, wie ich die Ränder entfernen könnte. Mach ich aber nicht mehr heute.

**Comment by lukashecke** [comment]
![Firestocks](https://user-images.githubusercontent.com/57808594/154594997-b680e7bf-f168-484d-a553-05e419ca65e1.svg)

Ich geh jetzt schlafen...

**Comment by lukashecke** [comment]
![Firestocks](https://user-images.githubusercontent.com/57808594/154795923-97fffa34-d308-44f0-a24c-9b8ff867a00b.png)

Hier noch einmal als PNG

**Comment by singhnamandeep** [comment]
![image](https://user-images.githubusercontent.com/43607156/154796007-37fc699e-67c0-4018-bb25-8935f51418f4.png)

**Comment by singhnamandeep** [comment]
[🅕🅘🅡🅔🅢🅣🅞🅒🅚🅢.docx](https://github.com/lukashecke/portfolio-management-software/files/8101927/default.docx)

**Comment by lukashecke** [comment]
Gemeinsam erstellte Logos liegen nun [hier](https://github.com/lukashecke/portfolio-management-software/tree/master/resources/Logo) ab. Bitt nur noch von da verwenden.
