### ISSUE TITLE
Programmname überlegen

### ISSUE THREAD

**Issue by lukashecke** [lukashecke/portfolio-management-software#3]

**Comment by lukashecke** [comment]
Irgendwas passendes einfach übersetzen und abändern (z.B. Profit in Latein)

**Comment by singhnamandeep** [comment]
OmeagaCoin oder AlphaStonks

**Comment by lukashecke** [comment]
Einfach nur Stonks?

**Comment by singhnamandeep** [comment]
StonksRepublic

**Comment by lukashecke** [comment]
PiggyBank oder wie auch immer das Item in Terraria heißt

**Comment by singhnamandeep** [comment]
StonX

**Comment by singhnamandeep** [comment]
ΩStonX

**Comment by lukashecke** [comment]
Haben uns ja jetzt für "Firestocks" entschieden :)
