### ISSUE TITLE
Programm kompiliert nicht, wenn von GitHub geklont.

### ISSUE THREAD

**Issue by lukashecke** [lukashecke/portfolio-management-software#32]

**Comment by lukashecke** [comment]
.gitignore überprüfen

**Comment by singhnamandeep** [comment]
Executing pre-compile tasks...
Cleaning output directories...
Running 'before' tasks
Checking sources
Parsing java... [portfolio-management-software-master]
java: Compilation failed: internal java compiler error
Errors occurred while compiling module 'portfolio-management-software-master'
error-prone compiler 2.6.0 was used to compile java sources
Finished, saving caches...
Compilation failed: errors: 1; warnings: 0
Executing post-compile tasks...
Synchronizing output directories...
17.02.2022 21:38 - Build completed with 1 error and 0 warnings in 3 sec, 659 ms

**Comment by lukashecke** [comment]
Repariert, bitte testen

**Comment by singhnamandeep** [comment]
Fixed
