### ISSUE TITLE
Datenbankschema in MYSQL Workbench umsetzen

### ISSUE THREAD

**Issue by lukashecke** [lukashecke/portfolio-management-software#35]

**Comment by singhnamandeep** [comment]
![image](https://user-images.githubusercontent.com/43607156/154805784-9e3a3bbb-9874-4859-9699-315ee61f008d.png)

**Comment by singhnamandeep** [comment]
Das umgesetzte Datenbankschema hab ich per Email an heckelukas@gmail.com geschickt. Es ist nicht möglich eine .sql Datei auf github als Kommentar hinzufügen.

**Comment by lukashecke** [comment]
Question war an Lehrer und Review unter uns. 
Ich schau mir das Schema zu Hause gleich an.

**Comment by lukashecke** [comment]
Passt
